# KG Store Reports

import grn_register_report
import dep_issue_register
import store_issue_slip
import pobill_from_store2_po
import dep_indent_to_issue
import grn_to_issue
import pobill_from_po_acc


# Store Low Proiority Reports

import issue_summary_from_mainst
import opening_stock
import new_opening_stock
import consumption_summary
import consumption_details_report
import closing_stock_report
import major_closing_stock_report
import open_stock_report
import mains_closing_stock_report
import kg_depindent_detail_report
import kg_pi_detail_report
import gate_pass_register
import kg_product_reg_report
import kg_serindent_detail_report
import kg_supplier_register
import kg_product_warranty_register
import profit_loss_report
import sales_register_report
#import sale_cash
#import kg_sales_reg_rep
